### ISSUE TITLE
TODO: Things to implement

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/blaze_tensor#2]
Here is an incomplete list of things that have to be implemented:

- Tensor operations
  - [ ] tensor transposition 
  - [ ] tensor/vector multiplication
  - [ ] tensor/matrix multiplication
  - [ ] tensor/tensor multiplication
  - [ ] tensor contractions

- Blaze datastructures
  - [ ] Sparse 3D tensors
  - [ ] `blaze::StaticTensor<T>`

- Blaze views
  - [ ] `blaze::PageSlices`
  - [ ] `blaze::RowSlices`
  - [ ] `blaze::ColumnSlices`
  - [ ] ColumnSlice, RowSlice, and PageSlice selections
